codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 70
        threshold: 10
    patch:
      default:
        target: 50
        threshold: 100
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  - "src/nibetaseries/_version.py"
  - "src/nibetaseries/conftest.py"
  - "**/test_*.py"
